-- Suppression des tables existantes
DROP TABLE IF EXISTS produit_forme_laboratoire;
DROP TABLE IF EXISTS type_categorie;
DROP TABLE IF EXISTS categorie_sous_categorie;
DROP TABLE IF EXISTS produit_symptome;
DROP TABLE IF EXISTS maladie_symptome;
DROP TABLE IF EXISTS produit_sous_categorie;
DROP TABLE IF EXISTS mouvement;
DROP TABLE IF EXISTS produit_forme;
DROP TABLE IF EXISTS produit;
DROP TABLE IF EXISTS type_mouvement;
DROP TABLE IF EXISTS mode_administration;
DROP TABLE IF EXISTS forme;
DROP TABLE IF EXISTS symptome;
DROP TABLE IF EXISTS sous_categorie;
DROP TABLE IF EXISTS categorie;
DROP TABLE IF EXISTS unite_mesure;
DROP TABLE IF EXISTS "type"; -- "type" est un mot clé réservé en PostgreSQL
DROP TABLE IF EXISTS maladie;
DROP TABLE IF EXISTS laboratoire;

-- Suppression des séquences existantes
DROP SEQUENCE IF EXISTS laboratoire_id_seq;
DROP SEQUENCE IF EXISTS maladie_id_seq;
DROP SEQUENCE IF EXISTS type_id_seq;
DROP SEQUENCE IF EXISTS unite_mesure_id_seq;
DROP SEQUENCE IF EXISTS categorie_id_seq;
DROP SEQUENCE IF EXISTS sous_categorie_id_seq;
DROP SEQUENCE IF EXISTS symptome_id_seq;
DROP SEQUENCE IF EXISTS forme_id_seq;
DROP SEQUENCE IF EXISTS mode_administration_id_seq;
DROP SEQUENCE IF EXISTS type_mouvement_id_seq;
DROP SEQUENCE IF EXISTS produit_id_seq;
DROP SEQUENCE IF EXISTS produit_forme_id_seq;
DROP SEQUENCE IF EXISTS mouvement_id_seq;
DROP SEQUENCE IF EXISTS produit_sous_categorie_id_seq;
DROP SEQUENCE IF EXISTS maladie_symptome_id_seq;
DROP SEQUENCE IF EXISTS produit_symptome_id_seq;
DROP SEQUENCE IF EXISTS categorie_sous_categorie_id_seq;
DROP SEQUENCE IF EXISTS type_categorie_id_seq;
DROP SEQUENCE IF EXISTS produit_forme_laboratoire_id_seq;