-- Suppression des tables existantes
DROP TABLE IF EXISTS produit_maladie;
DROP TABLE IF EXISTS produit_categorie_personne;
DROP TABLE IF EXISTS produit;
DROP TABLE IF EXISTS mode_administration;
DROP TABLE IF EXISTS forme;
DROP TABLE IF EXISTS unite_mesure;
DROP TABLE IF EXISTS categorie_personne;
DROP TABLE IF EXISTS maladie;
DROP TABLE IF EXISTS laboratoire;

-- Suppression des séquences existantes
DROP SEQUENCE IF EXISTS produit_maladie;
DROP SEQUENCE IF EXISTS produit_categorie_personne;
DROP SEQUENCE IF EXISTS produit;
DROP SEQUENCE IF EXISTS mode_administration;
DROP SEQUENCE IF EXISTS forme;
DROP SEQUENCE IF EXISTS unite_mesure;
DROP SEQUENCE IF EXISTS categorie_personne;
DROP SEQUENCE IF EXISTS maladie;
DROP SEQUENCE IF EXISTS laboratoire;